# Generated by Django 5.0.4 on 2024-05-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='choice_vote',
        ),
    ]
